export const TEST_CLAYS = [
    {
        clayId: 'clay1',
        name: 'clay1',
        manufacturer: 'clay1Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay2',
        name: 'clay2',
        manufacturer: 'clay2Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay3',
        name: 'clay3',
        manufacturer: 'clay3Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay4',
        name: 'clay4',
        manufacturer: 'clay4Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay5',
        name: 'clay5',
        manufacturer: 'clay5Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay6',
        name: 'clay6',
        manufacturer: 'clay6Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay7',
        name: 'clay7',
        manufacturer: 'clay7Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay8',
        name: 'clay8',
        manufacturer: 'clay8Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay9',
        name: 'clay9',
        manufacturer: 'clay9Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay10',
        name: 'clay10',
        manufacturer: 'clay10Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay11',
        name: 'clay11',
        manufacturer: 'clay11Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay12',
        name: 'clay12',
        manufacturer: 'clay12Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay13',
        name: 'clay13',
        manufacturer: 'clay13Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay14',
        name: 'clay14',
        manufacturer: 'clay14Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay15',
        name: 'clay15',
        manufacturer: 'clay15Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay16',
        name: 'clay16',
        manufacturer: 'clay16Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay17',
        name: 'clay17',
        manufacturer: 'clay17Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay18',
        name: 'clay18',
        manufacturer: 'clay18Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay19',
        name: 'clay19',
        manufacturer: 'clay19Maker',
        notes: 'a nice clay',
    },
    {
        clayId: 'clay20',
        name: 'clay20',
        manufacturer: 'clay20Maker',
        notes: 'a nice clay',
    },
];

export const TEST_GLAZES = [
    {
        GlazeId: 'Glaze1',
        name: 'Glaze1',
        manufacturer: 'Glaze1Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze2',
        name: 'Glaze2',
        manufacturer: 'Glaze2Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze3',
        name: 'Glaze3',
        manufacturer: 'Glaze3Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze4',
        name: 'Glaze4',
        manufacturer: 'Glaze4Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze5',
        name: 'Glaze5',
        manufacturer: 'Glaze5Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze6',
        name: 'Glaze6',
        manufacturer: 'Glaze6Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze7',
        name: 'Glaze7',
        manufacturer: 'Glaze7Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze8',
        name: 'Glaze8',
        manufacturer: 'Glaze8Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze9',
        name: 'Glaze9',
        manufacturer: 'Glaze9Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze10',
        name: 'Glaze10',
        manufacturer: 'Glaze10Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze11',
        name: 'Glaze11',
        manufacturer: 'Glaze11Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze12',
        name: 'Glaze12',
        manufacturer: 'Glaze12Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze13',
        name: 'Glaze13',
        manufacturer: 'Glaze13Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze14',
        name: 'Glaze14',
        manufacturer: 'Glaze14Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze15',
        name: 'Glaze15',
        manufacturer: 'Glaze15Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze16',
        name: 'Glaze16',
        manufacturer: 'Glaze16Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze17',
        name: 'Glaze17',
        manufacturer: 'Glaze17Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze18',
        name: 'Glaze18',
        manufacturer: 'Glaze18Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze19',
        name: 'Glaze19',
        manufacturer: 'Glaze19Maker',
        notes: 'a nice Glaze',
    },
    {
        GlazeId: 'Glaze20',
        name: 'Glaze20',
        manufacturer: 'Glaze20Maker',
        notes: 'a nice Glaze',
    },
];